package com.mapping;
// Generated 24/02/2016 11:52:11 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenerationTime;

/**
 * Search generated by hbm2java
 */
@Entity
@Table(name="search"
    ,catalog="twitteroperation"
)
public class Search  implements java.io.Serializable {


     private Long idsearch;
     private Registrobusqueda registrobusqueda;
     private Long id;
     private Integer estado;
     private Date registro;
     private String usuario;

    public Search() {
    }

	
    public Search(Registrobusqueda registrobusqueda) {
        this.registrobusqueda = registrobusqueda;
    }
    public Search(Registrobusqueda registrobusqueda, Long id, Integer estado, Date registro, String usuario) {
       this.registrobusqueda = registrobusqueda;
       this.id = id;
       this.estado = estado;
       this.registro = registro;
       this.usuario = usuario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idsearch", unique=true, nullable=false)
    public Long getIdsearch() {
        return this.idsearch;
    }
    
    public void setIdsearch(Long idsearch) {
        this.idsearch = idsearch;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idregistro", nullable=false)
    public Registrobusqueda getRegistrobusqueda() {
        return this.registrobusqueda;
    }
    
    public void setRegistrobusqueda(Registrobusqueda registrobusqueda) {
        this.registrobusqueda = registrobusqueda;
    }
    
    @Column(name="id")
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="estado")
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
   @Temporal(TemporalType.TIMESTAMP)
    @org.hibernate.annotations.Generated(value = GenerationTime.ALWAYS)
    @Column(name = "registro", length = 19, insertable = false, updatable = false, columnDefinition = "datetime")
    public Date getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(Date registro) {
        this.registro = registro;
    }
    
    @Column(name="usuario", length=45)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }




}


